# Generated by Django 3.0.5 on 2020-07-23 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200723_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorialseries',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.TutorialSeries', verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 21, 1, 6, 855044), verbose_name='date published'),
        ),
    ]
